--NHANVIENCOBAN
DROP PROCEDURE PROC_UPD_SDT;
CREATE OR REPLACE PROCEDURE PROC_UPD_SDT(SDT IN VARCHAR2)
AS
BEGIN
    IF SDT IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'SDT không ???c ?? tr?ng');
    END IF;
    IF LENGTH(SDT) > 10 THEN
        RAISE_APPLICATION_ERROR(-20002, 'S? ?I?N THO?I CH? CÓ 10 S?');
    END IF;
    
    UPDATE NHANSU 
    SET DIENTHOAI = SDT
    WHERE MANV = SYS_CONTEXT('USERENV','SESSION_USER');
    
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Không tìm th?y nhân viên t??ng ?ng');
    END IF;
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('L?i: ' || SQLCODE || ' - ' || SQLERRM);
END;
/



CREATE OR REPLACE FUNCTION FUNC_VAITRO(USRNAME VARCHAR2)
RETURN VARCHAR2
AS
    CURSOR CUR IS 
    (
        SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS
        WHERE UPPER(GRANTEE)=UPPER(USRNAME)
    );
    VAITRO1 VARCHAR2(20);
    STR VARCHAR2(1000);
    USR VARCHAR(100);
BEGIN
    OPEN CUR;
    --STR := 'alter session set "_ORACLE_SCRIPT"=true';
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        STR:=USR;
    END LOOP;
    RETURN STR;
END;
/
--TAO POLICY TREN BANG NHANVIEN
CREATE OR REPLACE FUNCTION VPD_NVCB_NHANSU(P_SCHEMA VARCHAR2,P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
    
    STR VARCHAR2(1000);
    USR VARCHAR(100);
BEGIN
    IF(UPPER(FUNC_VAITRO(USER))='NHANVIENCOBAN') THEN
        STR:='MANV = ''' || SYS_CONTEXT('USERENV','SESSION_USER') || '''';
        RETURN STR;
    END IF;
    RETURN '1=1';
END;
/
BEGIN
DBMS_RLS.DROP_POLICY(
 OBJECT_SCHEMA => 'ADMINQL',
 OBJECT_NAME =>'NHANSU',
 POLICY_NAME => 'POL_NVCB_NHANSU');
END;
/
BEGIN
    DBMS_RLS.ADD_POLICY(
        object_schema   => 'ADMINQL', 
        object_name     => 'NHANSU',   
        policy_name     => 'POL_NVCB_NHANSU',
        policy_function => 'VPD_NVCB_NHANSU',
        STATEMENT_TYPES=>'SELECT,UPDATE'
    );
END;
/
GRANT SELECT,UPDATE(DIENTHOAI) ON NHANSU TO NHANVIENCOBAN;
GRANT SELECT ON SINHVIEN TO NHANVIENCOBAN;
GRANT SELECT ON DONVI TO NHANVIENCOBAN;
GRANT SELECT ON HOCPHAN TO NHANVIENCOBAN;
GRANT SELECT ON KHMO TO NHANVIENCOBAN;
GRANT EXECUTE ON PROC_UPD_SDT TO NHANVIENCOBAN;




