-- Them IF
CREATE OR REPLACE FUNCTION VPD_NVCB_NHANSU(P_SCHEMA VARCHAR2,P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
    
    STR VARCHAR2(1000);
    USR VARCHAR(100);
BEGIN
    IF(UPPER(FUNC_VAITRO(USER))='NHANVIENCOBAN') THEN
        STR:='MANV = ''' || SYS_CONTEXT('USERENV','SESSION_USER') || '''';
        RETURN STR;
    ELSIF (UPPER(FUNC_VAITRO(USER))='GIANGVIEN') THEN
        STR:='MANV = ''' || SYS_CONTEXT('USERENV','SESSION_USER') || '''';
        RETURN STR;
    ELSIF (UPPER(FUNC_VAITRO(USER))='TRUONGDV') THEN
        STR:='MANV = ''' || SYS_CONTEXT('USERENV','SESSION_USER') || '''';
        RETURN STR;
    END IF;
    RETURN '1=1';
END;
/

BEGIN
    DBMS_RLS.ADD_POLICY(
        object_schema   => 'ADMINQL', 
        object_name     => 'NHANSU',   
        policy_name     => 'POL_NVCB_NHANSU',
        policy_function => 'VPD_NVCB_NHANSU',
        STATEMENT_TYPES=>'SELECT,UPDATE'
    );
END;
/
GRANT SELECT,UPDATE(DIENTHOAI) ON NHANSU TO NHANVIENCOBAN;
GRANT SELECT ON SINHVIEN TO NHANVIENCOBAN;
GRANT SELECT ON DONVI TO NHANVIENCOBAN;
GRANT SELECT ON HOCPHAN TO NHANVIENCOBAN;
GRANT SELECT ON KHMO TO NHANVIENCOBAN;
GRANT EXECUTE ON PROC_UPD_SDT TO NHANVIENCOBAN;

-- CS2
--GIANGVIEN
GRANT NHANVIENCOBAN TO GIANGVIEN;

CREATE OR REPLACE VIEW VIEW_GIANG_VIEN_PHANCONG AS
SELECT * FROM PHANCONG WHERE MAGV = SYS_CONTEXT('USERENV', 'SESSION_USER');
GRANT SELECT ON VIEW_GIANG_VIEN_PHANCONG TO GIANGVIEN;

CREATE OR REPLACE FUNCTION GIANGVIEN_UPDATE_DIEMSO
    (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2 AS 
    STR VARCHAR2(1000);
    USR VARCHAR2(100); 
BEGIN
    IF(UPPER(FUNC_VAITRO(USER))='GIANGVIEN') THEN
        STR:='MAGV = ''' || SYS_CONTEXT('USERENV','SESSION_USER') || '''';
    ELSIF (UPPER(FUNC_VAITRO(USER))='TRUONGDV') THEN
        STR:='MAGV = ''' || SYS_CONTEXT('USERENV','SESSION_USER') || '''';
    END IF;
    RETURN STR;
END;
/
BEGIN
DBMS_RLS.DROP_POLICY(
    OBJECT_SCHEMA =>'ADMINQL',
    OBJECT_NAME=>'DANGKY',
    POLICY_NAME =>'GIANGVIEN_UPDATE_POLICY'
);
END;
/
BEGIN
DBMS_RLS.ADD_POLICY(
    OBJECT_SCHEMA =>'ADMINQL',
    OBJECT_NAME=>'DANGKY',
    POLICY_NAME =>'GIANGVIEN_UPDATE_POLICY',
    POLICY_FUNCTION=>'GIANGVIEN_UPDATE_DIEMSO',
    STATEMENT_TYPES=>'SELECT, UPDATE',
    UPDATE_CHECK => TRUE
 );
END;
/
GRANT SELECT, UPDATE (DIEMTHI, DIEMQT, DIEMCK, DIEMTK) ON DANGKY TO GIANGVIEN;

CREATE OR REPLACE PROCEDURE PROC_UPDATE_DIEMSO (
    p_MASV VARCHAR2,
    p_MAGV VARCHAR2,
    p_MAHP VARCHAR2,
    p_HK INT,
    p_NAM NUMBER,
    p_MACT VARCHAR2,
    p_DIEMTHI NUMBER,
    p_DIEMQT NUMBER,
    p_DIEMCK NUMBER,
    p_DIEMTK NUMBER
) IS
BEGIN
    -- C?p nh?t ?i?m s?
    UPDATE DANGKY
    SET DIEMTHI = p_DIEMTHI,
        DIEMQT = p_DIEMQT,
        DIEMCK = p_DIEMCK,
        DIEMTK = p_DIEMTK
    WHERE MASV = p_MASV AND MAGV = p_MAGV AND MAHP = p_MAHP AND HK = p_HK AND
          NAM = p_NAM AND MACT = p_MACT;

    -- Ki?m tra xem có b?n ghi nào ???c c?p nh?t không
    IF SQL%ROWCOUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('Thông tin ??ng ký ?ã nh?p không ?úng');
    ELSE
        DBMS_OUTPUT.PUT_LINE('C?p nh?t ?i?m s? thành công.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('L?i khi c?p nh?t ?i?m s?: ' || SQLERRM);
END;
/
GRANT EXECUTE ON PROC_UPDATE_DIEMSO TO GIANGVIEN;
