alter session set current_schema =  ADMINQL;
--CS#3
--1
GRANT NHANVIENCOBAN TO GIAOVU;
--2
GRANT INSERT, UPDATE, SELECT ON SINHVIEN TO GIAOVU;

GRANT EXECUTE ON PROC_THEMSINHVIEN TO GIAOVU;

/
GRANT EXECUTE ON PROC_UPDATE_STUDENT TO GIAOVU;


GRANT INSERT, UPDATE, SELECT ON DONVI TO GIAOVU;
--THEM DON VI

GRANT EXECUTE ON PROC_THEMDONVI TO GIAOVU;
--UPDATE DONVI

/

GRANT EXECUTE ON PROC_UPDATEDONVI TO GIAOVU;
GRANT INSERT, UPDATE, SELECT ON HOCPHAN TO GIAOVU;
--insert HP


GRANT EXECUTE ON PROC_INSERTHOCPHAN TO GIAOVU;

--update hocphan

GRANT EXECUTE ON PROC_UPDATEHOCPHAN TO GIAOVU;

GRANT INSERT, UPDATE, SELECT ON KHMO TO GIAOVU;
--insert khmo


GRANT EXECUTE ON PROC_INSERT_KHMO TO GIAOVU;
--update KHMO

GRANT EXECUTE ON PROC_UPDATE_KHMO TO GIAOVU;

--3
GRANT SELECT ON PHANCONG TO GIAOVU;
--UPDATE ON PHANCONG

GRANT EXECUTE ON PROC_UPDATE_PHANCONG TO GIAOVU;
GRANT UPDATE ON PHANCONG TO GIAOVU;
--DANGKY GIAOVU

GRANT SELECT, INSERT, DELETE ON DANGKY TO GIAOVU;
--PROC INSERT DK
GRANT EXECUTE ON PROC_DELETE_DANGKY TO GIAOVU;
GRANT EXECUTE ON PROC_INSERT_DANGKY TO GIAOVU;
SELECT * FROM DANGKY;

--CS#5
--update ttcn
GRANT EXECUTE ON PROC_UPD_SDT TO TRUONGKHOA;
--update diem so 
GRANT EXECUTE ON PROC_UPDATE_DIEMSO TO TRUONGKHOA;
--UPDATE ON PHANCONG

GRANT EXECUTE ON PROC_UPDATE_PHANCONG TO TRUONGKHOA;

--proc xoa phancong

/
GRANT EXECUTE ON PROC_DELETE_PHANCONG TO TRUONGKHOA;


/
GRANT EXECUTE ON PROC_INSERT_PHANCONG TO TRUONGKHOA;
GRANT SELECT ON HOCPHAN TO TRUONGKHOA;
GRANT SELECT,INSERT, UPDATE, DELETE ON PHANCONG TO TRUONGKHOA;

--nhansu
--insert

GRANT EXECUTE ON PROC_INSERT_NHANSU TO TRUONGKHOA;


GRANT EXECUTE ON PROC_UPDATE_NHANSU TO TRUONGKHOA;

GRANT SELECT, INSERT, DELETE, UPDATE ON NHANSU TO TRUONGKHOA;
GRANT SELECT ANY TABLE TO TRUONGKHOA;


--GIANGVIEN

GRANT SELECT, UPDATE (DIEMTHI, DIEMQT, DIEMCK, DIEMTK) ON DANGKY TO GIANGVIEN;
