
--TAO POLICY TREN BANG NHANVIEN
GRANT SELECT,UPDATE(DIENTHOAI) ON NHANSU TO NHANVIENCOBAN;
GRANT SELECT ON SINHVIEN TO NHANVIENCOBAN;
GRANT SELECT ON DONVI TO NHANVIENCOBAN;
GRANT SELECT ON HOCPHAN TO NHANVIENCOBAN;
GRANT SELECT ON KHMO TO NHANVIENCOBAN;
GRANT EXECUTE ON PROC_UPD_SDT TO NHANVIENCOBAN;




