SELECT VALUE FROM V$OPTION WHERE PARAMETER='Oracle Label Security';
select status from dba_ols_status where name ='OLS_CONFIGURE_STATUS';
/
--EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS;
/
SHUTDOWN IMMEDIATE;
STARTUP;
/
ALTER PLUGGABLE DATABASE QLDLNOIBO OPEN READ WRITE;
ALTER SESSION SET CONTAINER=QLDLNOIBO;
--ALTER SESSION SET CONTAINER=CDB$ROOT;
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
DROP USER ADMINQL;
CREATE USER ADMINQL IDENTIFIED BY ADMINQL CONTAINER = CURRENT;
SHOW CON_NAME
GRANT CONNECT, RESOURCE TO ADMINQL;
ALTER USER LBACSYS IDENTIFIED BY LBACSYS ACCOUNT UNLOCK CONTAINER = ALL;
GRANT UNLIMITED TABLESPACE TO ADMINQL;
GRANT LBAC_DBA TO ADMINQL;
GRANT SELECT ANY DICTIONARY TO ADMINQL;

/
CREATE USER ADMINQL IDENTIFIED BY ADMINQL CONTAINER = CURRENT;
SHOW CON_NAME
CREATE USER AD_OLS IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE TO ADMINQL;
ALTER USER LBACSYS IDENTIFIED BY LBACSYS ACCOUNT UNLOCK CONTAINER = ALL;
GRANT UNLIMITED TABLESPACE TO ADMINQL;
GRANT LBAC_DBA TO AD_OLS;
GRANT SELECT ANY DICTIONARY TO AD_OLS;
GRANT LBAC_DBA TO ADMINQL;
GRANT SELECT ANY DICTIONARY TO ADMINQL;

/

GRANT EXECUTE ON sa_components TO ADMINQL WITH GRANT OPTION;
GRANT EXECUTE ON sa_SESSION TO ADMINQL WITH GRANT OPTION;
GRANT EXECUTE ON sa_user_admin TO ADMINQL WITH GRANT OPTION;
GRANT EXECUTE ON sa_label_admin TO ADMINQL WITH GRANT OPTION;
GRANT EXECUTE ON sa_policy_admin TO ADMINQL WITH GRANT OPTION;
GRANT EXECUTE ON sa_audit_admin  TO ADMINQL WITH GRANT OPTION;
GRANT EXECUTE ON SA_SYSDBA TO ADMINQL;
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMINQL;

GRANT CONNECT,RESOURCE TO ADMINQL; --C?P QUY?N CONNECT VÀ RESOURCE
GRANT UNLIMITED TABLESPACE TO ADMINQL; --C?P QUOTA CHO ADMIN_OLS
GRANT SELECT ANY DICTIONARY TO ADMINQL; --C?P QUY?N ??C DICTIONARY
 
GRANT DBA TO ADMINQL;
GRANT SELECT ON DBA_ROLE_PRIVS TO ADMINQL;
GRANT EXECUTE ANY PROCEDURE TO ADMINQL;
grant create procedure to ADMINQL;
GRANT CREATE USER TO ADMINQL;
GRANT CREATE SESSION TO ADMINQL;
GRANT ALL PRIVILEGES TO ADMINQL WITH ADMIN OPTION;
--alter session set current_schema =  ADMINQL;
GRANT SELECT ON DBA_ROLE_PRIVS TO ADMINQL;